<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ErrorLog>$(MSBuildProjectDirectory)\roslyn_report.sarif</ErrorLog>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
	</ItemGroup>

</Project>